### PR TITLE
Complete Guide - Part 3

### PR DESCRIPTION
**Pull request by youyuhsuan**
Feat: Implement responsive layout, fetch API data, time selection, homepage links, and image slideshow

Implemented responsive web design (RWD) layout for the attraction page based on Figma design. Utilized native HTML date input for date selection.

Fetched attraction details API (/api/attraction/{attractionId}) on page load and rendered them dynamically using JavaScript, aligning with Figma design specifications.

Added functionality for users to choose 上半天or 下半天 for their trip, updating pricing accordingly (NTD 2000 for 上半天, NTD 2500 for 下半天).

Added links to attraction blocks on the homepage, allowing users to navigate to the corresponding attraction page (/attraction/{attractionId}). Also added a link on the website title to return to the homepage.

Implemented an image slideshow effect on the attraction page, displaying multiple pictures for each attraction with left and right arrows for navigation.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Where is your testing URLs?

**Comment by youyuhsuan** [comment]
http://57.181.203.89:8000/

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by cwpeng** [comment]
Merge pull request after review approval.

**Pull request merged**
