### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by youyuhsuan**
http://57.181.203.89:8000/
老師麻煩了

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by youyuhsuan** [comment]
再麻煩了QQ

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Add link on 預定行程 text in the thankyou page.
- Could you tell me how you execute your server in the background, so that your server keeps running even if you close the terminal.

**Comment by youyuhsuan** [comment]
The command `nohup uvicorn app:app --host 0.0.0.0 --port 8000` is used to start a server using Uvicorn in the background,

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
